### ISSUE TITLE
SDM@K metric setting question etc.

### ISSUE THREAD

**Issue by Frost24K** [Yux1angJi/GTA-UAV#2]
Hi,
Thank you for sharing this excellent work. I have a few questions regarding the use of the dataset for my own research:

1. Why is the threshold in the SDM@K calculation set to 0.001? Is this value adjustable, or is it purely based on empirical findings?

2. I noticed that the project includes preparation code for the Visloc dataset, but I did not find any experimental results on the Visloc dataset in the paper. Could you clarify this discrepancy?

3. Could you provide details about the hardware configuration used for sampling the dataset?

Looking forward to your response.
Best.

**Comment by Yux1angJi** [comment]
Thanks for your interest in our work.

1. Yes, it is purely based on empirical findings. The original definition of SDM@K from [DenseUAV](https://github.com/Dmmm1997/DenseUAV) sets $s=5\times 10^3$. However, since the original definition is for lat. and lon. calculations, and here it is applied to meter-level distances, we empirically set this value to 0.001 to have a better numerical distinction.
2. The preparation codes are for public [UAV-VisLoc dataset](https://github.com/IntelliSensing/UAV-VisLoc), and we do have experimental results on Table.4. Since we did not conduct thorough selection and inspection on this dataset and only used a portion of it for the extension and validatino of our experimental setup, this part of the work has not been well organized yet and only serve as a reference.
3. Do you mean the GTAV simulation? This will not lead to significant resource consumption, and I believe a standard Windows PC can handle it.

**Comment by Frost24K** [comment]
Thank you for your prompt response. Your answer has cleared up my doubts, and I apologize for overlooking the evaluations on the Visloc dataset in Table 4.
Another question:
I was wondering if it would be possible to extend the dataset to include variations under different illumination and weather conditions, and use it as a test set to evaluate generalization performance. Would it be practical to modify these settings within the simulation?

Thank you!

**Comment by Yux1angJi** [comment]
That's an interesting idea. And yes, it's feasible. 
Maybe we could work on it together :)

**Comment by Frost24K** [comment]
Okay, i have sent the contact info to your email.
